# Generated by Django 5.2.17 on 2026-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
