# Generated by Django 5.2.17 on 2026-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicebooking_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='current_work',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
