# Generated by Django 5.2.17 on 2026-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicebooking_current_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='staff_location_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
