# Generated by Django 5.2.17 on 2026-09-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assistancerequest_customer_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
    ]
